import type { Score } from "../types";
import type { RenderSvgOptions } from "./svg";

export interface RenderHtmlOptions extends RenderSvgOptions {
  /** Override the document <title>. Defaults to the score title. */
  title?: string;
  /**
   * Embedded `.drumtab` source used by dynamic exports. Not serialized
   * for static exports.
   */
  source?: string;
}

/**
 * Wrap a pre-rendered SVG string in a single self-contained HTML
 * document — SVG is inlined and styled inline, so the result renders
 * identically in any browser without needing the Drumit runtime.
 */
export function wrapSvgInStaticHtml(
  svg: string,
  score: Score,
  options: RenderHtmlOptions = {},
): string {
  const title = options.title ?? score.title ?? "Drumit chart";
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: light; }
    body {
      margin: 0;
      padding: 24px;
      background: #fafaf9;
      font-family: 'Helvetica Neue', Arial, sans-serif;
      color: #1c1917;
    }
    main { max-width: 1200px; margin: 0 auto; }
    h1 {
      font-family: Georgia, 'Times New Roman', serif;
      font-weight: 600;
      font-size: 28px;
      margin: 0 0 16px;
    }
    .chart { background: #fff; border-radius: 16px; padding: 8px; box-shadow: 0 1px 3px rgba(0,0,0,.04); }
    .chart svg { display: block; width: 100%; height: auto; }
    footer { margin-top: 24px; font-size: 11px; color: #78716c; }
  </style>
</head>
<body>
  <main>
    <h1>${escapeHtml(title)}</h1>
    <div class="chart">${svg}</div>
    <footer>Generated by <a href="https://w-mai.github.io/Drumit/">Drumit</a></footer>
  </main>
</body>
</html>
`;
}

/**
 * Like `wrapSvgInStaticHtml`, but with an embedded transport that lets
 * the viewer play the chart through the Web Audio synth engine (no
 * network, no samples). Includes a Play / Stop button and the `.drumtab`
 * source for reference.
 *
 * The embedded script bundles just enough logic to parse and schedule
 * the score. To keep the HTML small, the runtime is reimplemented as a
 * tiny inline helper rather than shipping the full app bundle.
 */
export function wrapSvgInDynamicHtml(
  svg: string,
  score: Score,
  options: RenderHtmlOptions = {},
): string {
  const title = options.title ?? score.title ?? "Drumit chart";
  const source = options.source ?? "";
  const bpm = score.tempo?.bpm ?? 100;

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: light; }
    body {
      margin: 0;
      padding: 24px;
      background: #fafaf9;
      font-family: 'Helvetica Neue', Arial, sans-serif;
      color: #1c1917;
    }
    main { max-width: 1200px; margin: 0 auto; }
    header { display: flex; align-items: baseline; gap: 16px; margin-bottom: 16px; }
    h1 {
      font-family: Georgia, 'Times New Roman', serif;
      font-weight: 600;
      font-size: 28px;
      margin: 0;
    }
    .tempo { font-size: 12px; color: #78716c; }
    .controls { display: flex; gap: 8px; align-items: center; margin-bottom: 12px; }
    button {
      padding: 6px 14px;
      font-size: 13px;
      font-weight: 600;
      border-radius: 999px;
      border: 1px solid #e7e5e4;
      background: #fff;
      color: #1c1917;
      cursor: pointer;
    }
    button:hover { background: #fafaf9; }
    button[disabled] { opacity: .5; cursor: default; }
    button.primary { background: #1c1917; color: #fff; border-color: #1c1917; }
    button.primary:hover { background: #292524; }
    .chart { background: #fff; border-radius: 16px; padding: 8px; box-shadow: 0 1px 3px rgba(0,0,0,.04); }
    .chart svg { display: block; width: 100%; height: auto; }
    details { margin-top: 16px; }
    pre {
      background: #1c1917;
      color: #fef3c7;
      padding: 16px;
      border-radius: 12px;
      overflow: auto;
      font-size: 12px;
      line-height: 1.5;
    }
    footer { margin-top: 24px; font-size: 11px; color: #78716c; }
  </style>
</head>
<body>
  <main>
    <header>
      <h1>${escapeHtml(title)}</h1>
      <span class="tempo">♩ ${bpm} · ${score.meter.beats}/${score.meter.beatUnit}</span>
    </header>
    <div class="controls">
      <button id="play" class="primary" type="button">▶ Play</button>
      <button id="stop" type="button">■ Stop</button>
    </div>
    <div class="chart">${svg}</div>
    ${
      source
        ? `<details><summary>.drumtab source</summary><pre>${escapeHtml(source)}</pre></details>`
        : ""
    }
    <footer>Generated by <a href="https://w-mai.github.io/Drumit/">Drumit</a></footer>
  </main>
  <script id="drumtab-source" type="text/plain">${escapeHtml(source)}</script>
  <script>${EMBEDDED_PLAYER}</script>
</body>
</html>
`;
}

const EMBEDDED_PLAYER = `
// Minimal Web Audio drum synth + scheduler, enough to play back a
// .drumtab exported by Drumit. This runs entirely offline inside the
// exported HTML file. Keep this in sync with src/playback/synthEngine.ts
// conceptually — simplified for size.
(function () {
  const source = document.getElementById("drumtab-source");
  if (!source) return;
  const text = source.textContent || "";
  if (!text.trim()) return;
  const score = parseDrumtab(text);
  if (!score) return;
  const events = schedule(score);
  if (events.length === 0) return;

  const playBtn = document.getElementById("play");
  const stopBtn = document.getElementById("stop");
  if (!playBtn || !stopBtn) return;

  let ctx = null;
  let startTime = 0;
  let scheduled = [];
  let playing = false;

  function ensureCtx() {
    if (ctx) return ctx;
    const Ctor = window.AudioContext || window.webkitAudioContext;
    ctx = new Ctor();
    return ctx;
  }

  function play() {
    if (playing) return;
    const audio = ensureCtx();
    audio.resume();
    playing = true;
    startTime = audio.currentTime + 0.05;
    scheduled = events.map((e) => scheduleHit(audio, e, startTime));
    const endAt = startTime + events[events.length - 1].time + 1;
    setTimeout(() => { playing = false; }, (endAt - audio.currentTime) * 1000);
  }
  function stop() {
    if (!playing) return;
    playing = false;
    scheduled.forEach((s) => s && s.stop && s.stop());
    scheduled = [];
  }

  playBtn.addEventListener("click", play);
  stopBtn.addEventListener("click", stop);

  function scheduleHit(audio, e, base) {
    const t = base + e.time;
    return synthHit(audio, t, e.instrument, e.velocity);
  }

  // --- synth ---
  function synthHit(audio, t, instrument, vel) {
    const v = Math.max(0, Math.min(1, vel / 127));
    if (instrument === "kick") return synthKick(audio, t, v);
    if (instrument === "snare") return synthSnare(audio, t, v);
    if (instrument === "hihatClosed" || instrument === "hihatFoot") return synthHat(audio, t, v, 0.08);
    if (instrument === "hihatOpen" || instrument === "hihatHalfOpen") return synthHat(audio, t, v, 0.3);
    if (instrument === "ride" || instrument === "rideBell") return synthCym(audio, t, v, 0.6, 5200);
    if (instrument === "crashLeft" || instrument === "crashRight") return synthCym(audio, t, v, 1.2, 3600);
    if (instrument === "tomHigh") return synthTom(audio, t, v, 180);
    if (instrument === "tomMid") return synthTom(audio, t, v, 140);
    if (instrument === "floorTom") return synthTom(audio, t, v, 100);
    return null;
  }
  function env(audio, t, peak, decay) {
    const g = audio.createGain();
    g.gain.setValueAtTime(0, t);
    g.gain.linearRampToValueAtTime(peak, t + 0.003);
    g.gain.exponentialRampToValueAtTime(0.0001, t + decay);
    return g;
  }
  function synthKick(audio, t, v) {
    const osc = audio.createOscillator();
    osc.frequency.setValueAtTime(140, t);
    osc.frequency.exponentialRampToValueAtTime(45, t + 0.08);
    const g = env(audio, t, v, 0.28);
    osc.connect(g).connect(audio.destination);
    osc.start(t); osc.stop(t + 0.32);
    return osc;
  }
  function synthSnare(audio, t, v) {
    const nb = noiseBuffer(audio);
    const n = audio.createBufferSource(); n.buffer = nb;
    const bp = audio.createBiquadFilter(); bp.type = "bandpass"; bp.frequency.value = 1800;
    const g = env(audio, t, v * 0.8, 0.18);
    n.connect(bp).connect(g).connect(audio.destination);
    n.start(t); n.stop(t + 0.22);
    return n;
  }
  function synthHat(audio, t, v, decay) {
    const nb = noiseBuffer(audio);
    const n = audio.createBufferSource(); n.buffer = nb;
    const hp = audio.createBiquadFilter(); hp.type = "highpass"; hp.frequency.value = 7000;
    const g = env(audio, t, v * 0.35, decay);
    n.connect(hp).connect(g).connect(audio.destination);
    n.start(t); n.stop(t + decay + 0.05);
    return n;
  }
  function synthCym(audio, t, v, decay, centre) {
    const nb = noiseBuffer(audio);
    const n = audio.createBufferSource(); n.buffer = nb;
    const bp = audio.createBiquadFilter(); bp.type = "bandpass"; bp.frequency.value = centre;
    const g = env(audio, t, v * 0.4, decay);
    n.connect(bp).connect(g).connect(audio.destination);
    n.start(t); n.stop(t + decay + 0.05);
    return n;
  }
  function synthTom(audio, t, v, f) {
    const osc = audio.createOscillator();
    osc.frequency.setValueAtTime(f * 1.4, t);
    osc.frequency.exponentialRampToValueAtTime(f, t + 0.12);
    const g = env(audio, t, v * 0.7, 0.3);
    osc.connect(g).connect(audio.destination);
    osc.start(t); osc.stop(t + 0.34);
    return osc;
  }
  let cachedNoise = null;
  function noiseBuffer(audio) {
    if (cachedNoise) return cachedNoise;
    const len = audio.sampleRate * 0.5;
    cachedNoise = audio.createBuffer(1, len, audio.sampleRate);
    const data = cachedNoise.getChannelData(0);
    for (let i = 0; i < len; i++) data[i] = Math.random() * 2 - 1;
    return cachedNoise;
  }

  // --- tiny .drumtab parser (subset: headers + bars with beats + lanes) ---
  function parseDrumtab(src) {
    const lines = src.split(/\\r?\\n/);
    let tempo = 100, beats = 4;
    const bars = [];
    for (const raw of lines) {
      const line = raw.trim();
      if (!line || line.startsWith("#") || line.startsWith("[")) continue;
      const mTempo = line.match(/^tempo:\\s*(\\d+)/i);
      if (mTempo) { tempo = parseInt(mTempo[1], 10); continue; }
      const mMeter = line.match(/^meter:\\s*(\\d+)\\s*\\/\\s*(\\d+)/i);
      if (mMeter) { beats = parseInt(mMeter[1], 10); continue; }
      if (line.startsWith("|") || line.startsWith("|:")) {
        const body = line.replace(/^\\|:?\\s*/, "").replace(/\\s*:?\\|.*$/, "");
        const lanes = body.split(/\\s{2,}/).map(ch => ch.trim()).filter(Boolean);
        const bar = [];
        for (const lane of lanes) {
          const m = lane.match(/^(\\w+):\\s*(.+)$/);
          if (!m) continue;
          const inst = instAlias(m[1].toLowerCase());
          if (!inst) continue;
          const perBeat = m[2].split(/\\s*\\/\\s*/);
          bar.push({ instrument: inst, beats: perBeat });
        }
        bars.push(bar);
      }
    }
    return { tempo, beats, bars };
  }
  function instAlias(s) {
    const m = {
      bd:"kick", kick:"kick",
      sn:"snare", snare:"snare",
      hh:"hihatClosed", hhc:"hihatClosed", hihat:"hihatClosed",
      hho:"hihatOpen", ohh:"hihatOpen",
      hhh:"hihatHalfOpen",
      hhf:"hihatFoot",
      ride:"ride", rd:"ride",
      rb:"rideBell",
      cr:"crashLeft", crash:"crashLeft",
      cr2:"crashRight",
      t1:"tomHigh", tomhigh:"tomHigh",
      t2:"tomMid", tommid:"tomMid",
      ft:"floorTom", floortom:"floorTom",
    };
    return m[s];
  }
  function schedule(score) {
    const spb = 60 / score.tempo;
    const out = [];
    let cursor = 0;
    for (const bar of score.bars) {
      for (let b = 0; b < score.beats; b++) {
        const beatStart = cursor + b * spb;
        for (const lane of bar) {
          const tokens = parseTokens(lane.beats[b] || "-");
          const n = tokens.length;
          if (!n) continue;
          const step = spb / n;
          tokens.forEach((tok, i) => {
            if (!tok.hit) return;
            out.push({
              time: beatStart + i * step,
              instrument: lane.instrument,
              velocity: tok.velocity,
            });
          });
        }
      }
      cursor += score.beats * spb;
    }
    return out.sort((a,b) => a.time - b.time);
  }
  function parseTokens(s) {
    // Super simplified: expand each char as a slot. > → louder, ( ) ghost softer.
    let v = 96;
    if (/>/.test(s)) v = 120;
    if (/\\(/.test(s)) v = 40;
    const clean = s.replace(/[>()!~/fr]/gi, "").replace(/[RL]/gi, "");
    const tokens = [];
    for (const ch of clean) {
      if (ch === "-" || ch === "." || ch === " ") tokens.push({ hit: false, velocity: 0 });
      else if (ch === "o" || ch === "x" || ch === "X" || ch === "O") tokens.push({ hit: true, velocity: v });
    }
    return tokens;
  }
})();
`;

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
