import type { Score } from "../types";
import type { RenderSvgOptions } from "./svg";
import { PLAYER_BUNDLE } from "./player.bundle";

export interface RenderHtmlOptions extends RenderSvgOptions {
  /** Override the document <title>. Defaults to the score title. */
  title?: string;
  /**
   * Embedded `.drumtab` source used by dynamic exports. Not serialized
   * for static exports.
   */
  source?: string;
}

/**
 * Wrap a pre-rendered SVG string in a single self-contained HTML
 * document — SVG is inlined and styled inline, so the result renders
 * identically in any browser without needing the Drumit runtime.
 */
export function wrapSvgInStaticHtml(
  svg: string,
  score: Score,
  options: RenderHtmlOptions = {},
): string {
  const title = options.title ?? score.title ?? "Drumit chart";
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: light; }
    body {
      margin: 0;
      padding: 24px;
      background: #fafaf9;
      font-family: 'Helvetica Neue', Arial, sans-serif;
      color: #1c1917;
    }
    main { max-width: 1200px; margin: 0 auto; }
    h1 {
      font-family: Georgia, 'Times New Roman', serif;
      font-weight: 600;
      font-size: 28px;
      margin: 0 0 16px;
    }
    .chart { background: #fff; border-radius: 16px; padding: 8px; box-shadow: 0 1px 3px rgba(0,0,0,.04); }
    .chart svg { display: block; width: 100%; height: auto; }
    footer { margin-top: 24px; font-size: 11px; color: #78716c; }
  </style>
</head>
<body>
  <main>
    <h1>${escapeHtml(title)}</h1>
    <div class="chart">${svg}</div>
    <footer>Generated by <a href="https://w-mai.github.io/Drumit/">Drumit</a></footer>
  </main>
</body>
</html>
`;
}

/**
 * Like `wrapSvgInStaticHtml`, but with an embedded transport that lets
 * the viewer play the chart through the Web Audio synth engine (no
 * network, no samples). Includes a Play / Stop button and the `.drumtab`
 * source for reference.
 *
 * The embedded script bundles just enough logic to parse and schedule
 * the score. To keep the HTML small, the runtime is reimplemented as a
 * tiny inline helper rather than shipping the full app bundle.
 */
export function wrapSvgInDynamicHtml(
  svg: string,
  score: Score,
  options: RenderHtmlOptions = {},
): string {
  const title = options.title ?? score.title ?? "Drumit chart";
  const source = options.source ?? "";
  const bpm = score.tempo?.bpm ?? 100;

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: light; }
    body {
      margin: 0;
      padding: 24px;
      background: #fafaf9;
      font-family: 'Helvetica Neue', Arial, sans-serif;
      color: #1c1917;
    }
    main { max-width: 1200px; margin: 0 auto; }
    header { display: flex; align-items: baseline; gap: 16px; margin-bottom: 16px; }
    h1 {
      font-family: Georgia, 'Times New Roman', serif;
      font-weight: 600;
      font-size: 28px;
      margin: 0;
    }
    .tempo { font-size: 12px; color: #78716c; }
    .controls { display: flex; gap: 12px; align-items: center; margin-bottom: 12px; flex-wrap: wrap; }
    .tempo-control { display: inline-flex; gap: 6px; align-items: center; font-size: 12px; color: #44403c; }
    .tempo-control input[type="range"] { width: 160px; accent-color: #1c1917; }
    .tempo-control .value { min-width: 34px; font-variant-numeric: tabular-nums; font-weight: 600; color: #1c1917; }
    button {
      padding: 6px 14px;
      font-size: 13px;
      font-weight: 600;
      border-radius: 999px;
      border: 1px solid #e7e5e4;
      background: #fff;
      color: #1c1917;
      cursor: pointer;
    }
    button:hover { background: #fafaf9; }
    button[disabled] { opacity: .5; cursor: default; }
    button.primary { background: #1c1917; color: #fff; border-color: #1c1917; }
    button.primary:hover { background: #292524; }
    .chart { background: #fff; border-radius: 16px; padding: 8px; box-shadow: 0 1px 3px rgba(0,0,0,.04); }
    .chart svg { display: block; width: 100%; height: auto; }
    details { margin-top: 16px; }
    pre {
      background: #1c1917;
      color: #fef3c7;
      padding: 16px;
      border-radius: 12px;
      overflow: auto;
      font-size: 12px;
      line-height: 1.5;
    }
    footer { margin-top: 24px; font-size: 11px; color: #78716c; }
  </style>
</head>
<body>
  <main>
    <header>
      <h1>${escapeHtml(title)}</h1>
      <span class="tempo">♩ ${bpm} · ${score.meter.beats}/${score.meter.beatUnit}</span>
    </header>
    <div class="controls">
      <button id="play" class="primary" type="button">▶ Play</button>
      <button id="pause" type="button" disabled>⏸ Pause</button>
      <button id="stop" type="button" disabled>■ Stop</button>
      <label class="tempo-control">
        ♩ =
        <input id="tempo" type="range" min="40" max="260" step="1" value="${bpm}">
        <span id="tempo-value" class="value">${bpm}</span>
        BPM
      </label>
    </div>
    <div class="chart">${svg}</div>
    ${
      source
        ? `<details><summary>.drumtab source</summary><pre>${escapeHtml(source)}</pre></details>`
        : ""
    }
    <footer>Generated by <a href="https://w-mai.github.io/Drumit/">Drumit</a></footer>
  </main>
  <script id="drumtab-source" type="text/plain">${escapeHtml(source)}</script>
  <script>${PLAYER_BUNDLE}</script>
</body>
</html>
`;
}


function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
