#!/usr/bin/env bun
/**
 * Bundle the embedded-player entry point into an IIFE string and emit it
 * as a TypeScript module that `src/notation/exporters/html.ts` can
 * import. The output is committed to source so that consumers (CI, the
 * web app, sample generators) don't need esbuild at runtime.
 *
 * Usage:
 *   bun run scripts/build-player.ts
 *
 * Writes:
 *   src/notation/exporters/player.bundle.ts — export const PLAYER_BUNDLE = `...`;
 */
import { build } from "esbuild";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const entry = join(process.cwd(), "src/playback/embedded.ts");
const outPath = join(process.cwd(), "src/notation/exporters/player.bundle.ts");

const result = await build({
  entryPoints: [entry],
  bundle: true,
  format: "iife",
  target: "es2020",
  minify: true,
  write: false,
  // External nothing — everything is inlined into the IIFE.
  platform: "browser",
  treeShaking: true,
  legalComments: "none",
});

if (result.errors.length) {
  console.error(result.errors);
  process.exit(1);
}

const code = result.outputFiles[0].text;

// Escape backticks + $ so the code sits safely inside a template string.
const escaped = code
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const fileContent = `/**
 * Auto-generated by scripts/build-player.ts — do not edit by hand.
 * Run \`bun run player:bundle\` to regenerate after changes to
 * src/playback/embedded.ts (or any of its transitive deps).
 */
export const PLAYER_BUNDLE = \`${escaped}\`;
`;

writeFileSync(outPath, fileContent, "utf-8");
console.log(
  `wrote ${outPath} (${code.length} bytes of JS → ${fileContent.length} bytes of TS)`,
);
